sudo: false
language: node_js
node_js:
  # LTS
  - "8"
  - "10"
  - "12"
  - "14"
  - "node"
before_install:
  - npm install -g npm
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export DENO_INSTALL="$HOME/.deno"
  - export PATH="$DENO_INSTALL/bin:$PATH"
install:
  - npm install
script:
  - npm test
after_success:
  - npm run report-coverage

