name: ci

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: npm install
      - run: npm run fmt -- --check
      - run: npm test
      - run: npm report-coverage
